// STATE 13'S PAGES SAY WHAT THE PIPELINE SUPPORTS, AND THE QUESTION IS THE AUTHORED ONE.
//
// Both pages are GENERATED by docs/mockups/13-business-report.build.mjs, from
// three sources: the question as authored in tests/fixtures/bus-practice-paper.json,
// a sitting in 13-business-report.fixture.json, and the shipped contract and
// worker. This suite keeps the pages honest to those sources, the way t33 does for
// state 12, and adds the three things state 13 introduced:
//
//   - "What your marker was told to look for" is exactly what reportGuidance sends,
//     in its order, with nothing ticked or crossed, because the marker returns no
//     per-point verdict;
//   - the case study collapses once marked and is open in full while answering,
//     and in both it sits directly under the instruction that says "below";
//   - the marker's prose cites no figure the student did not write, because the
//     marker is never sent the case study and cannot know one.
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const fs = require("node:fs");
const path = require("node:path");
const A = require("../tools/contract/assessment.js");

let pass = 0, fail = 0;
const ok = (c, m) => { if (c) { pass++; } else { fail++; console.log("  FAIL:", m); } };
const ROOT = path.resolve(new URL("..", import.meta.url).pathname);
const read = f => fs.readFileSync(path.join(ROOT, f), "utf8");

const paper = JSON.parse(read("tests/fixtures/bus-practice-paper.json"));
const q = paper.sections[2].questions[0];
const fx = JSON.parse(read("docs/mockups/13-business-report.fixture.json"));
const marked = read("docs/mockups/13-business-report.html");
const answering = read("docs/mockups/13-business-report-answering.html");
const body = h => h.slice(h.indexOf("<body>"));
const unesc = s => s.replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&amp;/g, "&");
const text = h => unesc(body(h).replace(/<style[\s\S]*?<\/style>/g, "").replace(/<[^>]+>/g, " ")).replace(/\s+/g, " ");

console.log("--- 1. the question on the page is the authored question");
ok(A.normaliseFormat(q).format === "business_report", "the paper's q14 is still the business report");
for (const [name, h] of [["marked", marked], ["answering", answering]]) {
  ok(body(h).includes('<p class="instr">' + escHTML(q.instructions) + "</p>"),
     `${name}: the question's own instructions, verbatim`);
  ok(body(h).includes(escHTML(q.stimulus.text)), `${name}: the case study text, verbatim`);
  ok(body(h).includes(q.stimulus.img), `${name}: the authored chart, not a redrawing of it`);
  ok(body(h).includes('<h1 class="exam-prompt">' + escHTML(q.prompt) + "</h1>"), `${name}: the prompt, verbatim`);
  // "Use the case study below" has to be true: instruction, then case study, then prompt.
  const b = body(h), iI = b.indexOf('class="instr"'), iC = b.indexOf('class="case"'), iP = b.indexOf('class="exam-prompt"');
  ok(iI > 0 && iC > iI && iP > iC, `${name}: the case study sits directly under the instruction that says "below"`);
  ok(!/—/.test(text(h)) && !/—/.test(h.match(/<title>([^<]*)<\/title>/)[1]),
     `${name}: no em dash anywhere a student reads it, title included`);
}
function escHTML(s) { return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;"); }

console.log("--- 2. what the marker was told is what the marker is sent");
const rg = A.reportGuidance(q, []);
const told = [...body(marked).matchAll(/<ol class="told">([\s\S]*?)<\/ol>/g)][0];
const items = told ? [...told[1].matchAll(/<li>([\s\S]*?)<\/li>/g)].map(m => unesc(m[1])) : [];
ok(JSON.stringify(items) === JSON.stringify(rg.items),
   `the list is ASSESS.reportGuidance(q14).items, exactly and in order (${items.length} of ${rg.items.length})`);
ok(items.some(x => /report structure with headings/.test(x)),
   "including the marking point that names the genre");
const toldSect = (body(marked).match(/What your marker was told to look for[\s\S]*?<\/section>/) || [""])[0];
ok(!/[✓✗✔✘]/.test(toldSect) && !/class="(hit|miss|tick)/.test(toldSect),
   "nothing in it is ticked or crossed, because the marker returns no per-point verdict");
ok(/did not score them one by one/.test(toldSect), "and it says so, in words");
ok(!/What your marker was told/.test(answering), "the answering state does not show the marking points before the answer");

console.log("--- 3. two disclosures once marked, none while answering");
ok(/<details class="case">/.test(marked) && !/<details class="case"[^>]*\bopen\b/.test(marked),
   "marked: the case study is a disclosure, CLOSED by default");
ok(/<details class="submitted">/.test(marked) && !/<details class="submitted"[^>]*\bopen\b/.test(marked),
   "marked: so is the submitted response");
ok(/<figure class="case">/.test(answering) && !/<details/.test(body(answering)),
   "answering: the case study is open in full and nothing is collapsed, because it is what the report is written from");
ok((body(marked).match(/<textarea|<input/g) || []).length === 0 && !/contenteditable/.test(marked),
   "MARKED HAS NO EDITABLE FIELD AT ALL");
ok((body(answering).match(/<textarea/g) || []).length === 1, "answering has exactly one");
ok(/blank lines between sections/.test(answering) && !/between paragraphs/.test(answering),
   "and its placeholder says sections, as the app now does");

console.log("--- 4. the student's report, as typed");
const blocks = [...body(marked).matchAll(/<div class="response">([\s\S]*?)<\/div>/g)]
  .flatMap(m => [...m[1].matchAll(/<p>([\s\S]*?)<\/p>/g)].map(x => unesc(x[1])));
ok(blocks.join("\n\n") === fx.answer, "the collapsed response holds the submitted report BYTE-EXACTLY");
ok(/\.response p\{white-space:pre-line\}/.test(marked),
   "its line breaks render as typed, so a heading line stays on its own line");
ok(!/<h[2-6][^>]*>(Executive summary|Findings|Recommendations|Conclusion)</.test(body(marked)),
   "and nothing the student typed is promoted to a heading: structure is not inferred");
const words = fx.answer.trim().split(/\s+/).length;
ok(new RegExp("\\u00b7 " + words + " words").test(marked), `the word count is counted (${words})`);
const ta = answering.match(/<textarea[^>]*>([\s\S]*?)<\/textarea>/);
ok(ta && unesc(ta[1]) === fx.answer, "the answering field holds the same report, byte-exactly");

console.log("--- 5. the marker claims nothing it could not know");
// The marker is sent the student's response, the question and the report's own
// guidance. It is NOT sent the case study (the stimulus travels as a boolean, and
// the extended prompt never reads it). So a figure in the marker's prose that is
// not in the student's response is a figure the marker could not have had.
const markerProse = [fx.review.summary]
  .concat(fx.review.paragraphs.flatMap(p => p.sentences.flatMap(s => s.issues.flatMap(i => [i.head, i.why]))));
const nums = markerProse.join(" ").match(/\b\d[\d,.]*\b/g) || [];
ok(nums.length > 0, "the marker's prose does cite figures, so this check is not vacuous: " + nums.join(","));
ok(nums.every(n => fx.answer.includes(n)),
   "and every one of them is in the student's own report: " + nums.filter(n => !fx.answer.includes(n)).join(",") );
const caseOnly = ["delivery times have slipped", "for three years", "the owners want to keep all six stores"]
  .filter(p => !fx.answer.toLowerCase().includes(p));
ok(caseOnly.every(p => !markerProse.join(" ").toLowerCase().includes(p)),
   "and it repeats no case-study phrasing the student did not use");

console.log("--- 6. the same exclusions as state 12");
{
  const crits = [...body(marked).matchAll(/<li class="crit">([\s\S]*?)<\/li>/g)].map(m => m[1]);
  ok(crits.length === 4, "four criterion rows");
  ok(crits.every(c => !/class="ev"|<q>/.test(c)), "no criterion owns evidence or a quotation");
  ok(crits.every(c => !/\b\d+\s*\/\s*\d+\b/.test(c) && !/\bof \d+ marks?\b/.test(c)), "no criterion carries a mark");
  ok(crits.every(c => !/\b(met|partial|missing)\b/i.test(c)), "no criterion carries a status");
  const es = read("essay-content.js");
  const mc = es.slice(es.indexOf("business_studies")).match(/markingCriteria:\s*\[([\s\S]*?)\]/);
  const authored = mc ? [...mc[1].matchAll(/"([^"]+)"/g)].map(m => m[1]) : [];
  const shown = [...body(marked).matchAll(/<h3 class="critn">([^<]+)<\/h3>/g)].map(m => unesc(m[1]));
  ok(JSON.stringify(shown) === JSON.stringify(authored), "the criteria are the authored strings, casing and order intact");
  const t = text(marked);
  [["band", /\bbands?\b/i], ["ladder", /\bladder\b/i], ["Clear/Better/Band 6", /\bClear\b.*\bBetter\b/i],
   ["a grounding percentage", /\b\d{1,3}\s*%/], ["missing vocabulary", /missing[_ ]vocabulary/i]]
    .forEach(([name, re]) => ok(!re.test(t), "the page shows no " + name));
  ok(/In your response/.test(t) && /Across your response/.test(t), "both anchoring labels are on screen");
  const quotes = [...body(marked).matchAll(/<q>([\s\S]*?)<\/q>/g)].map(m => unesc(m[1]));
  ok(quotes.length === 3 && quotes.every(qq => fx.answer.includes(qq)),
     `every quotation (${quotes.length}) is the student's own sentence, verbatim`);
  ok(/>Try again</.test(marked) && !/>Submit for marking</.test(marked), "marked offers Try again, not Submit");
  ok(/>Submit for marking</.test(answering) && !/class="result"/.test(answering), "answering offers Submit and shows no mark");
}

console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
